[tool.poetry]
name = "witness-ward-client"
version = "0.1.0"
description = ""
authors = ["ManonMic <manon.michelet5@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
opencv-python = "^4.3"
pytest = "^6.0"
matplotlib = "^3.3"
multitimer = "^0.2.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
