[tool.poetry]
name = "witness-ward-client"
version = "0.1.0"
description = ""
authors = ["ManonMic <manon.michelet5@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"
opencv-python = "^4.3"
pytest = "^6.0"
matplotlib = "^3.3"
multitimer = "^0.2.0"
pycryptodome = "^3.9.8"
uuid0 = "^0.2.7"
decorator = "^4.4.2"
jsonrpc_requests = "^0.4.0"
bson = "^0.5.10"
ffmpeg-python = "^0.2.0"
watchdog = "^0.10.3"
kivy = "^1.11.1"
wmi = "^1.5.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
