[build-system]
requires = ["poetry_core"]
build-backend = "poetry.masonry.api"


[tool.poetry]
name = "wanvr"
description = "Witness Angel NVR"
version = "0.1"
license = "MIT"
readme = "Readme.rst"
authors = ["Pascal Chambon", "Manon Michelet", "Akram Bourichi"]
homepage = "https://github.com/WitnessAngel/witness-angel-nvr"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: Unix",
    "Operating System :: MacOS :: MacOS X",
]
include = ["CHANGELOG", "tests/*.py"]
exclude = ["_build", "__pycache__"]

[tool.poetry.dependencies]
python = ">=3.7,<=3.10"

# For now WA dependencies must be manually installed at selected versions !
wacryptolib = { git = "https://github.com/WitnessAngel/witness-angel-cryptolib.git", branch = "wanvr_stable" }
wacomponents = { git = "https://github.com/WitnessAngel/witness-angel-components.git", branch = "wanvr_stable" }

# Wacomponents dependencies
oscpy = "^0.5.0"
plyer = "^1.4"

# Graphic interface
Kivy = {version = "^2.0.0", extras = ["base"]}
kivymd = "^0.104.1"

# FIXME remove this asap!
watchdog = "0.10.3"

[tool.poetry.dev-dependencies]

# Test runners and plugins
pytest = "^4.5"
pytest-cov = "^2.7"
pytest-randomly = "^3.0"
pytest-deadfixtures = "^2.1"
pytest-timeout = "^1.3"
freezegun = "^0.3.12"
typeguard = "^2.10.0"

# Linters and formatters
black = {version = "^18.3-alpha.0", allow-prereleases = true}

